//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fantasy_team
    {
        public int team_id { get; set; }
        public int team_budget { get; set; }
        public int league_id { get; set; }
        public int user_id { get; set; }
        public int team_points { get; set; }
        public Nullable<int> player1 { get; set; }
        public Nullable<int> player2 { get; set; }
        public Nullable<int> player3 { get; set; }
        public Nullable<int> player4 { get; set; }
    
        public virtual League League { get; set; }
        public virtual User User { get; set; }
    }
}
