
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary2
{

using System;
    using System.Collections.Generic;
    
public partial class League
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public League()
    {

        this.Fantasy_team = new HashSet<Fantasy_team>();

        this.Match = new HashSet<Match>();

        this.Listed_in = new HashSet<Listed_in>();

    }


    public int league_id { get; set; }

    public string league_name { get; set; }

    public string league_picture { get; set; }

    public int games_played { get; set; }

    public string league_rules { get; set; }

    public string invite_url { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Fantasy_team> Fantasy_team { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Match> Match { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Listed_in> Listed_in { get; set; }

}

}
