
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary2
{

using System;
    using System.Collections.Generic;
    using System.Web.Http.Cors;

    public partial class Listed_in
{
        EnableCorsAttribute cors = new EnableCorsAttribute("*", "*", "*");
        public int user_id { get; set; }

    public string nickname { get; set; }

    public int league_id { get; set; }

    public System.DateTime registration_date { get; set; }



    public virtual League League { get; set; }

    public virtual Player Player { get; set; }

}

}
