
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary2
{

    using System;
    using System.Collections.Generic;
    using System.Web.Http.Cors;


    public partial class Smart_calc
    {
        EnableCorsAttribute cors = new EnableCorsAttribute("*", "*", "*");

        public int calc_id { get; set; }

        public int wins_pts { get; set; }

        public int goals_pts { get; set; }

        public int assists_pts { get; set; }

        public int pen_missed_minus_pts { get; set; }

        public int goals_recieved_minus_pts { get; set; }

    }

}
