
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary2
{

    using System;
    using System.Collections.Generic;
    using System.Web.Http.Cors;


    public partial class User
    {
        EnableCorsAttribute cors = new EnableCorsAttribute("*", "*", "*");
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {

            this.Active_in = new HashSet<Active_in>();

            this.Fantasy_team = new HashSet<Fantasy_team>();

            this.Player = new HashSet<Player>();

        }


        public int user_id { get; set; }

        public string email { get; set; }

        public string password { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Active_in> Active_in { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Fantasy_team> Fantasy_team { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Player> Player { get; set; }

    }

}
